version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rezuan_portfolio
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - pgsql

  nginx:
    image: nginx:latest
    container_name: rezuan_portfolio_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  pgsql:
    image: postgres:15
    container_name: rezuan_portfolio_pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rezuan_portfolio
      POSTGRES_USER: rezuan
      POSTGRES_PASSWORD: rezuan123
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    image: node:22
    container_name: rezuan_portfolio_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"

volumes:
  pgdata:
